[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.1.4"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[context.production]
  environment = { JEKYLL_ENV = "production" }

[context.deploy-preview]
  environment = { JEKYLL_ENV = "development" }
